version: "3"

services:
    mongodb:
        image: mongo:latest
        environment:
            - MONGO_INITDB_ROOT_USERNAME=user
            - MONGO_INITDB_ROOT_PASSWORD=pass
        volumes:
            - ./data/db:/data/db
            - ./data/tmp:/home
            - ./MONGODUMP/articles:/data/articles
        restart: always
